### ISSUE TITLE
Assessment of GSA's Ongoing Authorization process as it applies to Cloud.gov Platformed TTS System(s)

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1260]
## Implementation

- [ ] Review GSA Ongoing Authorization Documentation 
- [ ] Split out issues for follow-on tasks
- [ ] Rough estimate of workload for Minimum Viable Product

## Acceptance 

- [ ] Documented gaps on what TTS [systems] would need to have ongoing authorization

**Comment by afeld** [comment]
This came up in a conversation with @boberlas; sounds like there would be a decent amount of technical integration (logging, agents, etc.) with GSA Security required for this to be possible. Asked for some high-level points of what that would take, since I think it's a good idea regardless of Ongoing Authorization.

**Comment by JJediny** [comment]
Latest template: https://docs.google.com/document/d/1CAqtW5IoKlnIDfOP9TBklSVstfsRfb-P7IRyDZ9lvhQ/edit#

**Comment by afeld** [comment]
Deliverable here is a roadmap / gap analysis, nothing more.
